In [37]:
import torch as t
t.Tensor(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
pip install torch torchvision torchaudio

In [38]:
# 生成一个随机Tensor
x = t.rand(2, 3, 4)
x

tensor([[[0.6139, 0.5250, 0.2663, 0.4823],
         [0.2710, 0.7316, 0.5744, 0.6101],
         [0.8897, 0.3953, 0.8055, 0.4434]],

        [[0.3992, 0.5951, 0.1418, 0.9815],
         [0.1010, 0.7685, 0.1532, 0.0930],
         [0.9436, 0.6559, 0.9900, 0.9952]]])

In [39]:
# 查看x的形状
print(x.size())

print(x.size()[0], x.size()[1], x.size()[2])

torch.Size([2, 3, 4])
2 3 4


In [40]:
#两个Tensor相加
y = t.rand(2, 3, 4)
z = x + y
z

tensor([[[1.3572, 0.9911, 0.3879, 1.0980],
         [1.1191, 0.9839, 1.1505, 1.4815],
         [1.6654, 0.4094, 1.6125, 1.0769]],

        [[0.7692, 1.1587, 0.4174, 1.0043],
         [0.1080, 0.7859, 0.3691, 0.1333],
         [1.2520, 1.5130, 1.5858, 1.5905]]])

In [41]:
# 注意两个张量对应的维度要匹配
y1 = t.rand(3, 4, 2)
z1 = x + y1
z1

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

In [173]:
# 不是所有情况都可以广播
y2 = t.rand(2, 1, 2)# 2, 3, 4
z2 = x + y1
print(z2)
z2.size()

tensor([[[1.6158, 2.4099],
         [1.6914, 2.5418],
         [1.0842, 2.8695],
         [1.0661, 2.9857]],

        [[1.9948, 2.1169],
         [1.6392, 2.9650],
         [1.9776, 2.1294],
         [1.5117, 2.4440]],

        [[1.8684, 2.7351],
         [1.7210, 2.6772],
         [1.8509, 2.1567],
         [1.3382, 2.0610]]])


torch.Size([3, 4, 2])

In [42]:
#通过函数add实现加法
print(x)
print(t.add(x, y))

print(x.add(y))
print(x)

print(x.add_(y))## operator_   in_place 
print(x)


tensor([[[0.6139, 0.5250, 0.2663, 0.4823],
         [0.2710, 0.7316, 0.5744, 0.6101],
         [0.8897, 0.3953, 0.8055, 0.4434]],

        [[0.3992, 0.5951, 0.1418, 0.9815],
         [0.1010, 0.7685, 0.1532, 0.0930],
         [0.9436, 0.6559, 0.9900, 0.9952]]])
tensor([[[1.3572, 0.9911, 0.3879, 1.0980],
         [1.1191, 0.9839, 1.1505, 1.4815],
         [1.6654, 0.4094, 1.6125, 1.0769]],

        [[0.7692, 1.1587, 0.4174, 1.0043],
         [0.1080, 0.7859, 0.3691, 0.1333],
         [1.2520, 1.5130, 1.5858, 1.5905]]])
tensor([[[1.3572, 0.9911, 0.3879, 1.0980],
         [1.1191, 0.9839, 1.1505, 1.4815],
         [1.6654, 0.4094, 1.6125, 1.0769]],

        [[0.7692, 1.1587, 0.4174, 1.0043],
         [0.1080, 0.7859, 0.3691, 0.1333],
         [1.2520, 1.5130, 1.5858, 1.5905]]])
tensor([[[0.6139, 0.5250, 0.2663, 0.4823],
         [0.2710, 0.7316, 0.5744, 0.6101],
         [0.8897, 0.3953, 0.8055, 0.4434]],

        [[0.3992, 0.5951, 0.1418, 0.9815],
         [0.1010, 0.7685, 0.1532, 0.0930

In [43]:
#另外一个写法，结果输出到提前定义好的Tensor中
result = t.Tensor(2, 3, 4)
t.add(x, y, out = result)
result

tensor([[[2.1004, 1.4572, 0.5094, 1.7136],
         [1.9672, 1.2362, 1.7267, 2.3529],
         [2.4412, 0.4234, 2.4195, 1.7103]],

        [[1.1393, 1.7223, 0.6929, 1.0271],
         [0.1149, 0.8034, 0.5849, 0.1736],
         [1.5604, 2.3700, 2.1817, 2.1858]]])

In [7]:
# 函数名带下划线 x.add_(y)会改变x，不带下划线x.add(y) 返回一个新的Tensor，x不改变
print(x)
x.add(y)
print(x)
x.add_(y)
print(x)

tensor([[[0.4451, 0.0962, 1.2723, 0.8291],
         [1.2611, 0.8535, 1.3659, 1.1903],
         [1.3993, 1.2535, 0.6625, 1.1738]],

        [[0.9912, 1.3405, 0.9066, 1.2636],
         [1.1613, 1.4513, 1.0810, 0.9068],
         [0.2541, 1.2024, 1.1832, 1.6327]]])
tensor([[[0.4451, 0.0962, 1.2723, 0.8291],
         [1.2611, 0.8535, 1.3659, 1.1903],
         [1.3993, 1.2535, 0.6625, 1.1738]],

        [[0.9912, 1.3405, 0.9066, 1.2636],
         [1.1613, 1.4513, 1.0810, 0.9068],
         [0.2541, 1.2024, 1.1832, 1.6327]]])
tensor([[[0.6774, 0.1715, 2.2705, 0.9805],
         [2.2601, 1.3506, 2.3619, 1.4963],
         [2.3865, 1.9251, 1.1884, 1.9892]],

        [[1.1931, 2.2940, 1.5435, 1.7038],
         [2.1163, 2.1989, 1.1915, 1.1962],
         [0.4156, 1.9192, 1.4419, 2.4235]]])


In [8]:
a =t.ones(2, 3)
b = 3.0 * t.ones(2, 3)
c = a - b
print(c)

tensor([[-2., -2., -2.],
        [-2., -2., -2.]])


In [9]:
d = t.ones(2,2)
e = a - d

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [44]:
a = t.Tensor([[1,2], [3,4], [5, 6]])
print(a)

#数乘矩阵
b = 2.0 * a
print(b)

#对应点相乘，sum后即为卷积
c = a * b
print(c)
print(c.sum())######

# a: 3 * 2, b.t():2 * 3
# d: 3 * 3
d = a.mm(b.t())
print(d)


# a.t(): 2 * 3, b.t():3 * 2
# e: 2 * 2
e = a.t().mm(b)
print(e)

print(a.size(), b.size())
a.mm(b)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])
tensor([[ 2.,  8.],
        [18., 32.],
        [50., 72.]])
tensor(182.)
tensor([[ 10.,  22.,  34.],
        [ 22.,  50.,  78.],
        [ 34.,  78., 122.]])
tensor([[ 70.,  88.],
        [ 88., 112.]])
torch.Size([3, 2]) torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [11]:
a = t.Tensor([[1,2], [3,4], [5, 6]]) # 3 * 2
b = t.Tensor([[1, 2],[3,4],[5,6],[7,8]]) # 4 * 2

c = a.mm(b.t()) # 3 * 4 
print(c)


#如果矩阵大小不满足 x: i * n, y:n * j的方式，则出错
c = a.mm(b)

tensor([[ 5., 11., 17., 23.],
        [11., 25., 39., 53.],
        [17., 39., 61., 83.]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 4x2)

In [12]:
#A: 3 * 2
#x: 1 * 2
A = t.Tensor([[1,2], [3,4], [5, 6]]) 
x = t.Tensor([[1, 2]])
print(A)
print(x)

# A: 3*2; b.t(): 2 * 1
# 结果：3 * 1
c = A.mm(x.t())
print(c)

#x: 1 * 2, A.t(): 2 * 3
# 结果: 1 * 3
d = x.mm(A.t())
print(d)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.]])
tensor([[ 5.],
        [11.],
        [17.]])
tensor([[ 5., 11., 17.]])


In [45]:
import torch as t
a=t.Tensor([[[1,2,3],[4,5,6]]])
b=t.Tensor([1,2,3,4,5,6])

print(a.size())
print(b.size())

print(a.view(1,6))
print(b.view(1,6))


print(a.size())
print(b.size())

torch.Size([1, 2, 3])
torch.Size([6])
tensor([[1., 2., 3., 4., 5., 6.]])
tensor([[1., 2., 3., 4., 5., 6.]])
torch.Size([1, 2, 3])
torch.Size([6])


In [178]:
a=t.Tensor([[[1,2,3, 4],[5,6,7,8]]])
print(a)
print(a.size())
print('---------------------------------')
print(a.view(4,2))
print('---------------------------------')
print(a.view(2, 2 ,2))
print('---------------------------------')

tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
torch.Size([1, 2, 4])
---------------------------------
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
---------------------------------
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
---------------------------------


In [199]:
#因为是视图，所以发生了修改
c = a.view(2, 2 ,2)
c[0,0,0] = -1
print(a)

tensor([[[-1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.]]])


In [48]:
# Tensor的选取操作与numpy类似
x = t.rand(2,3,4)
print(x)

x[0, 0, :]

tensor([[[0.4457, 0.2665, 0.5816, 0.7822],
         [0.1515, 0.6697, 0.7244, 0.8637],
         [0.2203, 0.3986, 0.6592, 0.2722]],

        [[0.8131, 0.5206, 0.7370, 0.1588],
         [0.7189, 0.0197, 0.4226, 0.5261],
         [0.5736, 0.4399, 0.5709, 0.3668]]])


tensor([0.4457, 0.2665, 0.5816, 0.7822])

In [49]:
x[:, 0, 0] 

tensor([0.4457, 0.8131])

In [51]:
x[:, :, 0]

tensor([[0.4457, 0.1515, 0.2203],
        [0.8131, 0.7189, 0.5736]])

In [18]:
x[:,1:3, 2:4]

tensor([[[0.6296, 0.2885],
         [0.4374, 0.4617]],

        [[0.4501, 0.2051],
         [0.1279, 0.0084]]])

In [229]:
x = t.rand(2,3)
print(x)
y = t.rand(2,4)
print(y)
z = t.cat((x,y), dim=1)
print(z)

tensor([[0.2636, 0.6643, 0.3245],
        [0.1376, 0.1650, 0.1767]])
tensor([[0.0598, 0.4083, 0.4071, 0.3481],
        [0.3681, 0.5724, 0.2711, 0.5821]])
tensor([[0.2636, 0.6643, 0.3245, 0.0598, 0.4083, 0.4071, 0.3481],
        [0.1376, 0.1650, 0.1767, 0.3681, 0.5724, 0.2711, 0.5821]])


In [231]:
x = t.rand(1,1,2,3)
print("before squeezing\n", x, x.size())
x = t.squeeze(x)
print("after squeezing\n", x, x.size())

before squeezing
 tensor([[[[0.1797, 0.4137, 0.0305],
          [0.7431, 0.0329, 0.4445]]]]) torch.Size([1, 1, 2, 3])
after squeezing
 tensor([[0.1797, 0.4137, 0.0305],
        [0.7431, 0.0329, 0.4445]]) torch.Size([2, 3])


In [233]:
#PyTorch Tensor与Numpy之间的转换
#tensor->numpy
a = t.ones(2, 3, 4)#Tensor
print(a)
b = a.numpy()
b

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [235]:
# numpy --> Tensor
import numpy as np
a = np.ones(5)
b = t.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [237]:
# 上述转换中，Tensor和Numpy共享内容，所以修改一个另一个也随之改变

print(a)
b.add_(1) #注意是下划线add_
print(a)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]


In [243]:
x = t.rand(2,3)
y = t.rand(2,3)

#支持GPU，将x和y都转移到GPU中进行运算
# 在大规模数据复杂Tensor运算时，具有优势；
# 小规模数据时由于具有数据转移开销，CPU会更快一点

#本机器不支持GPU，不会运行以下代码
if t.cuda.is_available():
    x = x.cuda() #将张量x转移到GPU中
    y = y.cuda() #将张量y转移到GPU中
    z = x + y #在GPU中运算x + y
else:
    print("Not A")
    z = x + y
print(z)

Not A
tensor([[0.5322, 0.7454, 1.4098],
        [0.6225, 1.6208, 1.1990]])


In [245]:
#如果不进行判断，x.cuda()语句在没有GPU环境的情况下出错
x = x.cuda() #将张量x转移到GPU中
y = y.cuda() #将张量y转移到GPU中
x + y #在GPU中运算x + y

AssertionError: Torch not compiled with CUDA enabled

In [247]:
# 求函数 y= x^2 在x=3时的导数: y'(3) = dy/dx|x=3

x=t.tensor(3.0,requires_grad=True)
y=x.mul(x)

#判断x,y是否是可以求导的
print(x.requires_grad)
print(y.requires_grad)

#求导，通过backward函数来实现
y.backward()

#查看导数，也即所谓的梯度
print(x.grad)

True
True
tensor(6.)


In [249]:
# 练习
# 求y = max(0, x)在x=1和x=-1处的导数


#定义x=1.0 和y=max(0, x)
x = t.tensor(1.0, requires_grad=True)
y = t.max(x, t.zeros(1,1))

#调用backward并打印导数
y.backward()
print(x.grad)

# 改变x后需要重新执行y和backward
x = t.tensor(-1.0, requires_grad=True)
y = t.max(x, t.zeros(1,1))
y.backward()
print(x.grad)

tensor(1.)
tensor(0.)


In [251]:
# 求y = 1/x
x = t.tensor(0.5, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)

x = t.tensor(1.0, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)

x = t.tensor(2.0, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)



tensor(-4.)
tensor(-1.)
tensor(-0.2500)


In [27]:
# 求y = 1/\sqrt(x)
x = t.tensor(0.5, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

x = t.tensor(1.0, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

x = t.tensor(2.0, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

tensor(-1.4142)
tensor(-0.5000)
tensor(-0.1768)


In [28]:
# 求y = 1/\sqrt(x)
x = t.tensor(1.0, requires_grad=True)
g = t.sqrt(x)
y = t.reciprocal(g)

g.backward(retain_graph=True)
print(x.grad)


y.backward(retain_graph=True)
print(x.grad)


tensor(0.5000)
tensor(0.)


In [29]:
# f(x,y) = x^2 + 2 * y^2 + xy
# 在 (1.0, 1.0)处的导数
x = t.tensor(1.0, requires_grad=True)
y = t.tensor(1.0, requires_grad=True)

f = x.pow(2) + t.tensor(2.0).mul(y.pow(2)) + x.mul(y)
f.backward()
print(x.grad)
print(y.grad)

tensor(3.)
tensor(5.)


In [30]:
# f(x,y, z) = ln(e^x + e^y + e^z)
# 在 (0.0, 2.0, 5.0)处的导数
x = t.tensor(0.0, requires_grad=True)
y = t.tensor(2.0, requires_grad=True)
z = t.tensor(5.0, requires_grad=True)

f = t.log(t.exp(x) + t.exp(y) + t.exp(z))
f.backward()
print(x.grad)
print(y.grad)
print(z.grad)

tensor(0.0064)
tensor(0.0471)
tensor(0.9465)


In [3]:
# 注意：把x和b定义为一个2*1的矩阵，x.mm()是矩阵乘法
import torch as t
x = t.tensor([[1.0], [2.0]], requires_grad=True)

A = t.tensor([[1.0, 1.0], 
              [1.0, 2.0]])
b = t.tensor([[1.0], [0.0]])
print(x, A, b)
print()

f = x.t().mm(A).mm(x) + x.t().mm(b)
print(f)
print()
f.backward()
print(x.grad)

tensor([[1.],
        [2.]], requires_grad=True) tensor([[1., 1.],
        [1., 2.]]) tensor([[1.],
        [0.]])

tensor([[14.]], grad_fn=<AddBackward0>)

tensor([[ 7.],
        [10.]])


In [5]:
x = t.tensor([[1.0], [2.0]], requires_grad=True)
y = t.tensor([[3.0], [4.0]], requires_grad=True)

A = t.tensor([[1.0, 1.0], 
              [1.0, 2.0]])
b = t.tensor([[1.0], [0.0]])
print(x, y, A, b)
print()

f = x.t().mm(A).mm(y) + x.t().mm(b)
print(f)
print()
f.backward()
print(x.grad)
print(y.grad)

tensor([[1.],
        [2.]], requires_grad=True) tensor([[3.],
        [4.]], requires_grad=True) tensor([[1., 1.],
        [1., 2.]]) tensor([[1.],
        [0.]])

tensor([[30.]], grad_fn=<AddBackward0>)

tensor([[ 8.],
        [11.]])
tensor([[3.],
        [5.]])


In [7]:
# f(A) = x^T A y + x^T b
x = t.tensor([[1.0], [2.0]])
y = t.tensor([[3.0], [4.0]])

A = t.tensor([[2.0, 12.0], 
              [1.0, 2.0]], requires_grad=True)
b = t.tensor([[1.0], [0.0]])
print(x, y, A, b)
print()

f = x.t().mm(A).mm(y) + x.t().mm(b)
print(f)
print()
f.backward()
#print(x.grad)
#print(y.grad)
print(A.grad)

tensor([[1.],
        [2.]]) tensor([[3.],
        [4.]]) tensor([[ 2., 12.],
        [ 1.,  2.]], requires_grad=True) tensor([[1.],
        [0.]])

tensor([[77.]], grad_fn=<AddBackward0>)

tensor([[3., 4.],
        [6., 8.]])
