In [1]:
import torch as t
t.Tensor(3, 4)
print(t.__version__)

2.7.0+cpu


In [31]:
# 生成一个随机Tensor
x = t.rand(2, 3, 4)
x

tensor([[[0.6862, 0.1404, 0.5759, 0.0975],
         [0.3727, 0.9210, 0.8898, 0.1087],
         [0.9427, 0.0550, 0.5798, 0.9759]],

        [[0.9131, 0.9198, 0.1288, 0.7288],
         [0.1218, 0.1987, 0.9134, 0.9135],
         [0.2459, 0.1575, 0.3379, 0.4578]]])

In [33]:
# 查看x的形状
print(x.size())

print(x.size()[0], x.size()[1], x.size()[2])

torch.Size([2, 3, 4])
2 3 4


In [35]:
#两个Tensor相加
y = t.rand(2, 3, 4)
z = x + y
z

tensor([[[1.3477, 0.9416, 1.2259, 0.9429],
         [0.8617, 1.2446, 1.3937, 0.6304],
         [1.1212, 0.2298, 1.3218, 1.4356]],

        [[1.3775, 1.1209, 0.5950, 1.5023],
         [0.5283, 0.4836, 1.5175, 1.2425],
         [0.7684, 0.6490, 1.2174, 0.6276]]])

In [37]:
# 注意两个张量对应的维度要匹配
y1 = t.rand(3, 4, 2)
z1 = x + y1
z1

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

In [39]:
#通过函数add实现加法
print(t.add(x, y))

tensor([[[1.3477, 0.9416, 1.2259, 0.9429],
         [0.8617, 1.2446, 1.3937, 0.6304],
         [1.1212, 0.2298, 1.3218, 1.4356]],

        [[1.3775, 1.1209, 0.5950, 1.5023],
         [0.5283, 0.4836, 1.5175, 1.2425],
         [0.7684, 0.6490, 1.2174, 0.6276]]])


In [41]:
x = t.rand(2,3,4)
y = t.rand(1,3,1)
z = x + y
print(x.size())
print(y.size())
print(z.size())

torch.Size([2, 3, 4])
torch.Size([1, 3, 1])
torch.Size([2, 3, 4])


In [43]:
x = t.rand(2,3,4)
y = t.rand(1,3,2)
z = x + y
print(x.size())
print(y.size())
print(z.size())

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

In [45]:
#另外一个写法，结果输出到提前定义好的Tensor中
result = t.Tensor(2, 3, 4)
x = t.rand(2, 3, 4)
y = t.rand(2, 3, 4)
t.add(x, y, out = result)
result

tensor([[[0.9585, 1.2435, 1.2089, 0.6691],
         [1.0728, 0.7058, 1.3123, 0.5184],
         [1.4150, 1.2051, 1.0735, 1.0385]],

        [[0.7554, 1.0544, 1.3630, 1.2955],
         [1.7007, 1.7571, 0.8237, 0.6010],
         [1.0906, 1.1719, 1.0333, 1.8185]]])

In [47]:
# 函数名带下划线 x.add_(y)会改变x，不带下划线x.add(y) 返回一个新的Tensor，x不改变
print(x)
x.add(y)
print(x)
x.add_(y)
print(x)

tensor([[[0.3912, 0.9108, 0.9038, 0.3977],
         [0.8235, 0.6576, 0.7737, 0.4148],
         [0.6547, 0.4639, 0.6549, 0.2668]],

        [[0.1422, 0.0686, 0.8640, 0.3267],
         [0.7307, 0.7678, 0.3851, 0.0465],
         [0.3102, 0.8771, 0.3160, 0.8350]]])
tensor([[[0.3912, 0.9108, 0.9038, 0.3977],
         [0.8235, 0.6576, 0.7737, 0.4148],
         [0.6547, 0.4639, 0.6549, 0.2668]],

        [[0.1422, 0.0686, 0.8640, 0.3267],
         [0.7307, 0.7678, 0.3851, 0.0465],
         [0.3102, 0.8771, 0.3160, 0.8350]]])
tensor([[[0.9585, 1.2435, 1.2089, 0.6691],
         [1.0728, 0.7058, 1.3123, 0.5184],
         [1.4150, 1.2051, 1.0735, 1.0385]],

        [[0.7554, 1.0544, 1.3630, 1.2955],
         [1.7007, 1.7571, 0.8237, 0.6010],
         [1.0906, 1.1719, 1.0333, 1.8185]]])


In [49]:
a =t.ones(2, 3)
b = 3.0 * t.ones(2, 3)
c = a - b
print(c)

tensor([[-2., -2., -2.],
        [-2., -2., -2.]])


In [51]:
d = t.ones(2,2)
e = a - d

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [53]:
a = t.Tensor([[1,2], [3,4], [5, 6]])
print(a)

#数乘矩阵
b = 2.0 * a
print(b)

#对应点相乘，sum后即为卷积
c = a * b
print(c)
print(c.sum())

# a: 3 * 2, b.t():2 * 3
# d: 3 * 3
d = a.mm(b.t())
print(d)


# a.t(): 2 * 3, b.t():3 * 2
# e: 2 * 2
e = a.t().mm(b)
print(e)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])
tensor([[ 2.,  8.],
        [18., 32.],
        [50., 72.]])
tensor(182.)
tensor([[ 10.,  22.,  34.],
        [ 22.,  50.,  78.],
        [ 34.,  78., 122.]])
tensor([[ 70.,  88.],
        [ 88., 112.]])


In [55]:
a = t.Tensor([[1,2], [3,4], [5, 6]]) # 3 * 2
b = t.Tensor([[1, 2],[3,4],[5,6],[7,8]]) # 4 * 2

c = a.mm(b.t()) # 3 * 4 
print(c)


#如果矩阵大小不满足 x: i * n, y:n * j的方式，则出错
c = a.mm(b)

tensor([[ 5., 11., 17., 23.],
        [11., 25., 39., 53.],
        [17., 39., 61., 83.]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 4x2)

In [57]:
#A: 3 * 2
#x: 1 * 2
A = t.Tensor([[1,2], [3,4], [5, 6]]) 
x = t.Tensor([[1, 2]])
print(A)
print(x)

# A: 3*2; b.t(): 2 * 1
# 结果：3 * 1
c = A.mm(x.t())
print(c)

#x: 1 * 2, A.t(): 2 * 3
# 结果: 1 * 3
d = x.mm(A.t())
print(d)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.]])
tensor([[ 5.],
        [11.],
        [17.]])
tensor([[ 5., 11., 17.]])


In [59]:
import torch as t
a=t.Tensor([[[1,2,3],[4,5,6]]])
b=t.Tensor([1,2,3,4,5,6])

print(a.view(1,6))
print(b.view(1,6))

tensor([[1., 2., 3., 4., 5., 6.]])
tensor([[1., 2., 3., 4., 5., 6.]])


In [61]:
a=t.Tensor([[[1,2,3, 4],[5,6,7,8]]])
print(a)
print('---------------------------------')
print(a.view(4,2))
print('---------------------------------')
print(a.view(2, 2 ,2))
print('---------------------------------')

tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
---------------------------------
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
---------------------------------
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
---------------------------------


In [ ]:
# Tensor的选取操作与numpy类似
x = t.rand(2,3,4)
print(x)
x[0, 0, :]  #有几个区间就有几个中括号

tensor([[[0.1918, 0.1022, 0.7519, 0.1538],
         [0.4982, 0.1233, 0.7954, 0.8056],
         [0.0992, 0.6927, 0.1815, 0.8829]],

        [[0.6970, 0.2224, 0.1487, 0.0361],
         [0.8382, 0.6988, 0.8047, 0.8188],
         [0.6358, 0.5353, 0.6387, 0.3271]]])


tensor([0.1918, 0.1022, 0.7519, 0.1538])

In [65]:
x[:, 0, 0] 

tensor([0.1918, 0.6970])

In [67]:
x[:, :, 0]

tensor([[0.1918, 0.4982, 0.0992],
        [0.6970, 0.8382, 0.6358]])

In [69]:
x[:,1:3, 2:4]

tensor([[[0.7954, 0.8056],
         [0.1815, 0.8829]],

        [[0.8047, 0.8188],
         [0.6387, 0.3271]]])

In [71]:
x1 = t.rand(2,2)
x2 = t.rand(2,2)
print(x1)
print(x2)

tensor([[0.6763, 0.2648],
        [0.9791, 0.2431]])
tensor([[0.2827, 0.9928],
        [0.0866, 0.9988]])


In [73]:
y = t.cat((x1, x2), dim=0)
print(y)

tensor([[0.6763, 0.2648],
        [0.9791, 0.2431],
        [0.2827, 0.9928],
        [0.0866, 0.9988]])


In [75]:
y = t.cat((x1,x2), dim=1)
print(y)

tensor([[0.6763, 0.2648, 0.2827, 0.9928],
        [0.9791, 0.2431, 0.0866, 0.9988]])


In [77]:
y = x1.unsqueeze(0)
print(y)
print(y.size())

tensor([[[0.6763, 0.2648],
         [0.9791, 0.2431]]])
torch.Size([1, 2, 2])


In [79]:
y = x1.squeeze(0)
print(y)
print(y.size())

tensor([[0.6763, 0.2648],
        [0.9791, 0.2431]])
torch.Size([2, 2])


In [81]:
y = t.chunk(x1, 2)
print(y)

(tensor([[0.6763, 0.2648]]), tensor([[0.9791, 0.2431]]))


In [83]:
y = t.rand(2,3)
print(y)

tensor([[0.1144, 0.7650, 0.9883],
        [0.7439, 0.5985, 0.8692]])


In [85]:
y1 = t.reshape(y, (3, 2))
print(y1)

y1[0,0] = 0

print(y)

tensor([[0.1144, 0.7650],
        [0.9883, 0.7439],
        [0.5985, 0.8692]])
tensor([[0.0000, 0.7650, 0.9883],
        [0.7439, 0.5985, 0.8692]])


In [87]:
y1 = y.reshape(1, -1)
print(y1)

tensor([[0.0000, 0.7650, 0.9883, 0.7439, 0.5985, 0.8692]])


In [89]:
#PyTorch Tensor与Numpy之间的转换
#tensor->numpy
a = t.ones(2, 3, 4)
b = a.numpy()
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [91]:
# numpy --> Tensor
import numpy as np
a = np.ones(5)
b = t.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [93]:
# 上述转换中，Tensor和Numpy共享内容，所以修改一个另一个也随之改变

print(a)
b.add_(1) #注意是下划线add_
print(a)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]


In [95]:
#支持GPU，将x和y都转移到GPU中进行运算
# 在大规模数据复杂Tensor运算时，具有优势；
# 小规模数据时由于具有数据转移开销，CPU会更快一点

#本机器不支持GPU，不会运行以下代码
if t.cuda.is_available():
    x = x.cuda() #将张量x转移到GPU中
    y = y.cuda() #将张量y转移到GPU中
    z = x + y #在GPU中运算x + y
else:
    z = x + y
print(z)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 2

In [97]:
#如果不进行判断，x.cuda()语句在没有GPU环境的情况下出错
x = x.cuda() #将张量x转移到GPU中
y = y.cuda() #将张量y转移到GPU中
x + y #在GPU中运算x + y

AssertionError: Torch not compiled with CUDA enabled

In [99]:
# 求函数 y= x^2 在x=3时的导数: y'(3) = dy/dx|x=3

x=t.tensor(3.0,requires_grad=True)
y=x.mul(x)

#判断x,y是否是可以求导的
print(x.requires_grad)
print(y.requires_grad)

#求导，通过backward函数来实现
y.backward()

#查看导数，也即所谓的梯度
print(x.grad)

True
True
tensor(6.)


In [101]:
# 练习
# 求y = max(0, x)在x=1和x=-1处的导数


#定义x=1.0 和y=max(0, x)
x = t.tensor(1.0, requires_grad=True)
y = t.max(x, t.zeros(1,1))

#调用backward并打印导数
y.backward()
print(x.grad)

# 改变x后需要重新执行y和backward
x = t.tensor(-1.0, requires_grad=True)
y = t.max(x, t.zeros(1,1))
y.backward()
print(x.grad)

tensor(1.)
tensor(0.)


In [103]:
# 求y = 1/x
x = t.tensor(0.5, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)

x = t.tensor(1.0, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)

x = t.tensor(2.0, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)



tensor(-4.)
tensor(-1.)
tensor(-0.2500)


In [105]:
# 求y = 1/\sqrt(x)
x = t.tensor(0.5, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

x = t.tensor(1.0, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

x = t.tensor(2.0, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

tensor(-1.4142)
tensor(-0.5000)
tensor(-0.1768)


In [107]:
# 求y = 1/\sqrt(x)
x = t.tensor(1.0, requires_grad=True)
g = t.sqrt(x)
y = t.reciprocal(g)

g.backward(retain_graph=True)
print(x.grad)


y.backward(retain_graph=True)
print(x.grad)


tensor(0.5000)
tensor(0.)


In [109]:
# f(x,y) = x^2 + 2 * y^2 + xy
# 在 (1.0, 1.0)处的导数
x = t.tensor(1.0, requires_grad=True)
y = t.tensor(1.0, requires_grad=True)

f = x.pow(2) + t.tensor(2.0).mul(y.pow(2)) + x.mul(y)
f.backward()
print(x.grad)
print(y.grad)

tensor(3.)
tensor(5.)


In [111]:
# f(x,y, z) = ln(e^x + e^y + e^z)
# 在 (0.0, 2.0, 5.0)处的导数
x = t.tensor(0.0, requires_grad=True)
y = t.tensor(2.0, requires_grad=True)
z = t.tensor(5.0, requires_grad=True)

f = t.log(t.exp(x) + t.exp(y) + t.exp(z))
f.backward()
print(x.grad)
print(y.grad)
print(z.grad)

tensor(0.0064)
tensor(0.0471)
tensor(0.9465)


In [113]:
# 注意：把x和b定义为一个2*1的矩阵，x.mm()是矩阵乘法
import torch as t
x = t.tensor([[1.0], [2.0]], requires_grad=True)

A = t.tensor([[1.0, 1.0], 
              [1.0, 2.0]])
b = t.tensor([[1.0], [0.0]])
print(x, A, b)
print()

f = x.t().mm(A).mm(x) + x.t().mm(b)
print(f)
print()
f.backward()
print(x.grad)

tensor([[1.],
        [2.]], requires_grad=True) tensor([[1., 1.],
        [1., 2.]]) tensor([[1.],
        [0.]])

tensor([[14.]], grad_fn=<AddBackward0>)

tensor([[ 7.],
        [10.]])


In [115]:

x = t.tensor([[1.0], [2.0]], requires_grad=True)
y = t.tensor([[3.0], [4.0]], requires_grad=True)

A = t.tensor([[1.0, 1.0], 
              [1.0, 2.0]])
b = t.tensor([[1.0], [0.0]])
print(x, y, A, b)
print()

f = x.t().mm(A).mm(y) + x.t().mm(b)
print(f)
print()
f.backward()
print(x.grad)
print(y.grad)

tensor([[1.],
        [2.]], requires_grad=True) tensor([[3.],
        [4.]], requires_grad=True) tensor([[1., 1.],
        [1., 2.]]) tensor([[1.],
        [0.]])

tensor([[30.]], grad_fn=<AddBackward0>)

tensor([[ 8.],
        [11.]])
tensor([[3.],
        [5.]])


In [117]:
# f(A) = x^T A y + x^T b
x = t.tensor([[1.0], [2.0]])
y = t.tensor([[3.0], [4.0]])

A = t.tensor([[2.0, 12.0], 
              [1.0, 2.0]], requires_grad=True)
b = t.tensor([[1.0], [0.0]])
print(x, y, A, b)
print()

f = x.t().mm(A).mm(y) + x.t().mm(b)
print(f)
print()
f.backward()
#print(x.grad)
#print(y.grad)
print(A.grad)

tensor([[1.],
        [2.]]) tensor([[3.],
        [4.]]) tensor([[ 2., 12.],
        [ 1.,  2.]], requires_grad=True) tensor([[1.],
        [0.]])

tensor([[77.]], grad_fn=<AddBackward0>)

tensor([[3., 4.],
        [6., 8.]])
